[package]
name = "game2048"
version = "0.1.0"
author = ["Ceyhun Cakar <cakar.ceyhun@gmail.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

